import GlassControl from './GlassControl';
import PinSound,{PinSoundProvider} from './PinSound';
import {lazy,Suspense,useEffect,useState} from 'react';
import {BrowserRouter,Link,NavLink,Route,Routes,useLocation,useNavigate} from 'react-router-dom';
import {ArrowRight,Mic,BookOpen,Box,ArrowUpRight,Menu,X,RotateCcw,ChevronRight} from 'lucide-react';
import {convert,dots,newSession} from './core';
import Cell from './Cell';
import {Lab} from './Lab';
import {Device,Judges,Engineering,Project,Instructions} from './InfoPages';
import {SpeechProvider,VoiceTools,getHealth,useSpeech} from './Speech';
const Practice=lazy(()=>import('./Practice'));const Results=lazy(()=>import('./Results'));const Checks=lazy(()=>import('./Checks'));
const NAV=[['/','მთავარი'],['/lab','სცადე'],['/learn','სწავლა'],['/practice','ტესტი'],['/results','შედეგები'],['/device','მოწყობილობა'],['/judges','ჟიურისთვის']];
function Home(){const [text,setText]=useState('დედა');const cells=convert(text),valid=cells.length>0&&cells.every(c=>c.mask!==null);return <><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="short-line"/>ქართული ბრაილი · ისწავლე და გამოსცადე</p><h1>სიტყვიდან<br/><span>ბრაილამდე.</span></h1><p className="hero-description">თქვი სიტყვა, აღმოაჩინე მისი წერტილები და ივარჯიშე შენს ტემპში.</p><div className="actions hero-actions"><Link className="button primary" to="/lab"><Mic size={19}/>სცადე ხმით<ArrowRight size={18}/></Link><Link className="button" to="/practice">დაიწყე ბრაილის ტესტი<ArrowUpRight size={18}/></Link></div><div className="hero-quick"><div className="section-heading"><label htmlFor="home-word">შენი პირველი სიტყვა</label><span className="pill">ცოცხალი გარდაქმნა</span></div><div className="home-input-row"><input id="home-word" maxLength={40} value={text} onChange={e=>setText(e.target.value)} placeholder="დაწერე ქართული სიტყვა"/><Link aria-label="სიტყვის ლაბორატორიაში გახსნა" to={`/lab?text=${encodeURIComponent(text)}`}><ArrowRight size={20}/></Link></div>{valid?<div className="home-braille">{cells.slice(0,8).map((c,i)=><div key={i}><Cell mask={c.mask!} small audible/><span>{c.char===' '?'␣':c.char}</span></div>)}{cells.length>8&&<Link to={`/lab?text=${encodeURIComponent(text)}`}>+{cells.length-8}</Link>}</div>:<p className="input-help">გამოიყენე ქართული ასოები და სივრცე. {cells.some(c=>c.mask===null)?'სხვა სიმბოლოების გარდაქმნა არ ხდება.':''}</p>}<small>ერთი ასო — ექვსი წერტილი. ეკრანული მიმოხილვა.</small></div><div className="hero-footnote"><span className="status-dot"/>პროგრამული დემო · ფიზიკური მოწყობილობა დამზადების პროცესშია</div></div><div className="hero-device"><div className="render-panel-top"><span>01 / მოწყობილობის დიზაინი</span><Box size={20}/></div><img src="/assets/device/device-overview-original.jpeg" alt="მოწყობილობის საერთო ხედი — გუნდის მიერ მოწოდებული SolidWorks-ის რენდერი"/><div className="device-caption"><div><span className="eyebrow">ექვსწერტილიანი უჯრა</span><strong>იდეა, რომელსაც შეგიძლია შეეხო.</strong><span>SolidWorks-ის რენდერი · ჯერ დიზაინის ეტაპზე</span></div><Link to="/device" aria-label="მოწყობილობის დიზაინის ნახვა"><ArrowUpRight size={24}/></Link></div><div className="render-side-label">დიზაინი → პროგრამული სიმულაცია → ფიზიკური გამოცდა</div></div></section>
 <section className="path-section"><div className="section-heading"><div><p className="eyebrow">შენი სასწავლო გზა</p><h2>აღმოაჩინე. გაიგე. სცადე.</h2></div><Link className="text-link" to="/instructions">როგორ მუშაობს<ArrowRight size={16}/></Link></div><div className="path-cards">{[['01','ისწავლე ანბანი','გაეცანი 33 ქართულ ასოს და თითოეულის წერტილებს.','/learn',BookOpen],['02','გამოსცადე ცოდნა','ამოიცანი ბრაილი ან თავად ააწყვე ნიმუში.','/practice',Mic],['03','გამოიკვლიე მოწყობილობა','ნახე საწყისი რენდერები და ცოცხალი სიმულაცია.','/device',Box]].map(([n,title,description,to,Icon])=>{const I=Icon as typeof Box;return <Link className="path-card" key={String(n)} to={String(to)}><div className="section-heading"><span>{String(n)}</span><I size={22}/></div><h3>{String(title)}</h3><p>{String(description)}</p><span className="card-arrow"><ArrowRight size={20}/></span></Link>;})}</div></section><section className="home-evidence"><div><p className="eyebrow">„ლეონარდო და ვინჩი“ · პროექტის მასალები</p><h2>შეაფასე ის, რაც მუშაობს.</h2><p>პროგრამული ცდა, რეალური შედეგები და დიზაინის პირველწყაროები — ერთ სივრცეში.</p></div><Link className="button light" to="/judges">ჟიურის გზამკვლევი<ArrowRight size={18}/></Link></section></>;}
function Layout(){const location=useLocation(),navigate=useNavigate(),speech=useSpeech();const [menu,setMenu]=useState(false),[ready,setReady]=useState<string>('მზადყოფნა მოწმდება'),[visitor,setVisitor]=useState(0),[storageError,setStorageError]=useState('');useEffect(()=>{setMenu(false);speech.stop();window.scrollTo(0,0);if(location.pathname!=='/')document.getElementById('main')?.focus({preventScroll:true});},[location.pathname]);useEffect(()=>{let active=true;getHealth().then(h=>{if(active)setReady(h.model_state==='ready'?'ხმის მოდელი მზადაა':'ხმის მოდელი მზად არ არის');}).catch(()=>{if(active)setReady('ტექსტური რეჟიმი ხელმისაწვდომია');});return()=>{active=false;};},[]);
 function resetVisitor(){try{newSession();speech.stop();setVisitor(v=>v+1);navigate('/');setStorageError('');}catch{setStorageError('ბრაუზერის საცავი მიუწვდომელია. ჩართე ადგილობრივი შენახვა.');}}
 return <><a className="skip-link" href="#main">მთავარ შინაარსზე გადასვლა</a><header className="site-header"><Link className="brand" to="/" aria-label="ბრაილის სასწავლო პლატფორმა — მთავარი"><span className="brand-symbol" aria-hidden="true">{[0,1,2,3,4,5].map(i=><i key={i}/>)}</span><span>ბრაილი<small>სასწავლო პლატფორმა</small></span></Link><nav aria-label="მთავარი ნავიგაცია" className={menu?'open':''}>{NAV.map(([to,title])=><NavLink key={to} to={to} end={to==='/'}>{title}</NavLink>)}</nav><div className="header-actions"><GlassControl/><Link className="help-link" to="/instructions">ინსტრუქცია<ArrowUpRight size={14}/></Link><button className="menu-button" aria-label={menu?'მენიუს დახურვა':'მენიუს გახსნა'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><div className="utility-bar"><div><span className="status-dot"/>{ready}<Link to="/checks">შემოწმება<ChevronRight size={12}/></Link></div><PinSound/><button onClick={resetVisitor}><RotateCcw size={13}/>ახალი ვიზიტორი</button></div>{storageError&&<p role="alert" className="error">{storageError}</p>}<main id="main" tabIndex={-1} className={location.pathname==='/'?'home-main':'page-main'} key={visitor}><Suspense fallback={<p className="loading">გვერდი იტვირთება…</p>}><Routes><Route path="/" element={<Home/>}/><Route path="/lab" element={<Lab/>}/><Route path="/learn" element={<Lab learn/>}/><Route path="/practice" element={<Practice/>}/><Route path="/results" element={<Results/>}/><Route path="/device" element={<Device/>}/><Route path="/judges" element={<Judges/>}/><Route path="/engineering" element={<Engineering/>}/><Route path="/checks" element={<Checks/>}/><Route path="/instructions" element={<Instructions/>}/><Route path="/project" element={<Project/>}/><Route path="*" element={<section className="empty"><h1>გვერდი ვერ მოიძებნა</h1><Link to="/">მთავარზე დაბრუნება</Link></section>}/></Routes></Suspense></main><footer><div className="footer-top"><Link className="brand" to="/">ბრაილის სასწავლო პლატფორმა</Link><div><Link to="/project">პროექტი და წყაროები</Link><Link to="/engineering">მეთოდოლოგია</Link><Link to="/checks">შემოწმებები</Link></div></div><div className="footer-bottom"><p>ვიზუალური და აუდიტორული სწავლა · პროგრამული დემო · არ ცვლის ტაქტილურ კითხვას</p><VoiceTools/></div></footer></>;
}
export default function App(){return <BrowserRouter><SpeechProvider><PinSoundProvider><Layout/></PinSoundProvider></SpeechProvider></BrowserRouter>;}
