import {useState} from 'react';
import {CheckCircle2,AlertCircle,RefreshCw,Volume2} from 'lucide-react';
import fixtures from '../../data/fixtures.json';
import {convert,unicode,evaluate,appendChecks,technicalTests,BUILD,REVISION,type TechnicalTestResult,download,answerText} from './core';
import {getHealth,Recorder,useSpeech,type Health} from './Speech';
export default function Checks(){const [health,setHealth]=useState<Health|null>(null),[error,setError]=useState(''),[runs,setRuns]=useState(technicalTests()),[raw,setRaw]=useState(''),[reference,setReference]=useState(''),[bench,setBench]=useState<string|null>(null);const speech=useSpeech();
 async function checkHealth(){try{setHealth(await getHealth());setError('');}catch{setHealth(null);setError('სერვისი მიუწვდომელია. გაუშვი ადგილობრივი სერვერი და ხელახლა სცადე.');}}
 function run(){const results:{name:string;passed:boolean;detail:string}[]=[...fixtures.letters.map(([char,mask,braille])=>({name:`ასო ${char}`,passed:convert(String(char))[0].mask===mask&&unicode(Number(mask))===braille,detail:`დამოუკიდებელი ნიმუში: ${mask} / ${braille}`})),...fixtures.words.map(f=>({name:`სიტყვა ${f.text}`,passed:JSON.stringify(convert(f.text).map(c=>c.mask))===JSON.stringify(f.masks),detail:f.unicode})),{name:'პასუხის შეფასების განსხვავება',passed:evaluate('დედა','დედა')&&!evaluate('დედა','მამა'),detail:'სწორი და არასწორი პასუხის განსხვავება'},{name:'უცნობი სიმბოლო',passed:convert('ა1')[1].mask===null,detail:'ციფრს ნიმუში არ ენიჭება'}];const rows:TechnicalTestResult[]=results.map(r=>({...r,id:crypto.randomUUID(),schema:1,build:BUILD,timestamp:new Date().toISOString()}));appendChecks(rows);setRuns(technicalTests());}
 return <><div className="page-heading"><div><p className="eyebrow">მზადყოფნა და პროგრამული შემოწმება</p><h1>შეამოწმე დემოს დაწყებამდე</h1><p>აქ მოწმდება პროგრამული ფუნქციები. ფიზიკური მოწყობილობის გამოცდა ჯერ არ ჩატარებულა.</p></div></div><div className="two-columns"><section className="panel"><p className="eyebrow">ხმოვანი სერვისი</p><h2>მიკროფონი და ქართული ხმა</h2><button className="button" onClick={()=>void checkHealth()}><RefreshCw size={17}/>მზადყოფნის შემოწმება</button>{error&&<p className="error" role="alert">{error}</p>}{health&&<dl className="status-list"><dt>ამოცნობა</dt><dd>{health.model_state==='ready'?'მოდელი ჩატვირთულია':health.model_state==='loading'?'მოდელი იტვირთება':'მოდელი ვერ ჩაიტვირთა'}</dd><dt>ძრავა</dt><dd>{health.engine} / {health.model} / ka</dd><dt>გამოთვლა</dt><dd>{health.device} / {health.compute_type}</dd><dt>ადგილობრივი ხმა</dt><dd>{health.voice_available?health.voice_engine:'ქართული ხმა არ არის ხელმისაწვდომი'}</dd><dt>შემოწმება</dt><dd>{new Date(health.timestamp).toLocaleString('ka-GE')}</dd></dl>}<div className="actions"><button className="button" onClick={()=>speech.speak('გამარჯობა. ეს არის ბრაილის სასწავლო პლატფორმა.')}><Volume2 size={17}/>ხმის მოსმენა</button><button className="button subtle" onClick={speech.stop}>ხმის შეწყვეტა</button></div><p className="small-note">ხმა: {speech.engine??'ხელმისაწვდომობა მოწმდება მოთხოვნისას'}. მოსმენის ხარისხი შეაფასე რეალურ დინამიკზე.</p><Recorder onTranscript={e=>{setRaw(e.raw);setBench(null);}}/>{raw&&<div className="transcript"><strong>რეალური ტრანსკრიპტი</strong><p>{raw}</p></div>}</section><section className="panel"><p className="eyebrow">ამოცნობის ცალკე შემოწმება</p><h2>წაკითხული ფრაზის შედარება</h2><p>შეიყვანე ფრაზა და წაიკითხე მიკროფონით. ეტალონი მხოლოდ შედარებისთვის გამოიყენება და ამომცნობ ძრავას არ გადაეცემა.</p><label>ეტალონური ფრაზა<input value={reference} onChange={e=>{setReference(e.target.value);setBench(null);}} maxLength={160}/></label><button className="button" disabled={!raw||!reference.trim()} onClick={()=>{const match=answerText(raw)===answerText(reference);const detail=`ეტალონი: ${reference}; ნედლი: ${raw}`;const row:TechnicalTestResult={schema:1,id:crypto.randomUUID(),build:BUILD,timestamp:new Date().toISOString(),name:'ASR — სრული ტექსტის დამთხვევა',passed:match,detail};appendChecks([row]);setRuns(technicalTests());setBench(match?'სრული ტექსტი ემთხვევა ეტალონს.':'სრული ტექსტი არ ემთხვევა ეტალონს.');}}>ნედლი ტექსტის შედარება</button>{bench&&<p role="status">{bench}</p>}<p className="small-note">ერთ ფრაზაზე დამთხვევა საერთო ამოცნობის სიზუსტეს არ ადგენს. ცალკეული ასოები და სხვადასხვა მოსაუბრე დამატებით შეამოწმე.</p></section></div>
 <section className="panel section-space"><div className="section-heading"><div><p className="eyebrow">დამოუკიდებელი ნიმუშები</p><h2>მაპინგი და შეფასების წესები</h2></div><button className="button primary" onClick={run}>შემოწმებების გაშვება</button></div><p>33 ასო, 3 სიტყვა და შეფასების ორი წესი · Liblouis {REVISION.slice(0,8)} · ვერსია {BUILD}</p>{runs.length===0?<p className="empty">ამ ბრაუზერში შემოწმება ჯერ არ გაშვებულა.</p>:<><div className="check-results">{runs.slice(-45).map(r=><div key={r.id} className={r.passed?'check-pass':'check-fail'}>{r.passed?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>}<div><strong>{r.name}</strong><small>{r.detail} · {new Date(r.timestamp).toLocaleString('ka-GE')}</small></div></div>)}</div><button className="button" onClick={()=>download('software-checks.json',JSON.stringify(runs,null,2),'application/json')}>ტექნიკური ჩანაწერების ექსპორტი</button></>}
 </section><section className="callout"><div><h2>ფიზიკური შემოწმებები — ჯერ არ ჩატარებულა</h2><p>ამძრავების ტემპერატურა, ენერგომოხმარება, მექანიკური გამართულობა, ტაქტილური ძალა და მომხმარებლებთან გამოცდა პროგრამული სიმულაციით არ მოწმდება.</p></div></section></>;
}
