import {useEffect,useRef,useState} from 'react';
import {ZoomIn,ZoomOut,X,RotateCcw,ExternalLink} from 'lucide-react';
export const IMAGES=[{src:'/assets/device/device-overview-original.jpeg',title:'მოწყობილობის საერთო ხედი',caption:'მოწყობილობის საერთო ხედი — SolidWorks-ის რენდერი'},{src:'/assets/device/device-mechanism-original.jpeg',title:'შიდა მექანიზმი',caption:'შიდა მექანიზმის დეტალი — საპროექტო ვიზუალიზაცია'},{src:'/assets/device/device-top-cell-original.jpeg',title:'ექვსი წერტილის ზედაპირი',caption:'ექვსწერტილიანი ზედაპირის დეტალი — SolidWorks-ის რენდერი'}];
export function Gallery(){const [selected,setSelected]=useState(0),[open,setOpen]=useState(false),[scale,setScale]=useState(1),[pos,setPos]=useState({x:0,y:0});const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);const current=IMAGES[selected];
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 const reset=()=>{setScale(1);setPos({x:0,y:0});};const close=()=>{setOpen(false);reset();trigger.current?.focus();};
 return <section className="gallery"><div className="gallery-stage"><img src={current.src} alt={current.caption}/><button ref={trigger} className="button light gallery-zoom" onClick={()=>{reset();setOpen(true);}}><ZoomIn size={17}/>გადიდება</button><span className="image-tag">SolidWorks-ის რენდერი</span></div><div className="thumbnails">{IMAGES.map((im,i)=><button key={im.src} aria-pressed={i===selected} onClick={()=>setSelected(i)}><img src={im.src} alt=""/><span>{im.title}</span></button>)}</div><p className="caption">{current.caption}<br/>გუნდის მიერ მოწოდებული SolidWorks-ის რენდერი</p>
 <dialog ref={dialog} className="lightbox" onCancel={e=>{e.preventDefault();close();}} onClose={()=>{if(open)close();}}><div className="lightbox-header"><h2>{current.title}</h2><button className="icon-button" aria-label="გალერეის დახურვა" onClick={close}><X/></button></div><div className="zoom-stage" tabIndex={0} aria-label="გადიდებული რენდერი; გადაადგილება ისრებით, პლუსი და მინუსი ზომისთვის" onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();setPos(p=>({x:p.x+(e.key==='ArrowLeft'?30:e.key==='ArrowRight'?-30:0),y:p.y+(e.key==='ArrowUp'?30:e.key==='ArrowDown'?-30:0)}));}if(e.key==='+'||e.key==='=')setScale(s=>Math.min(4,s+.25));if(e.key==='-')setScale(s=>Math.max(1,s-.25));}}><img src={current.src} alt={current.caption} style={{transform:`translate(${pos.x}px,${pos.y}px) scale(${scale})`}}/></div><div className="actions"><button className="button" aria-label="რენდერის მოახლოება" onClick={()=>setScale(s=>Math.min(4,s+.25))}><ZoomIn/></button><button className="button" aria-label="რენდერის დაშორება" onClick={()=>setScale(s=>Math.max(1,s-.25))}><ZoomOut/></button><button className="button" onClick={reset}><RotateCcw size={17}/>აღდგენა</button><button className="button" aria-label="მარცხნივ გადაადგილება" onClick={()=>setPos(p=>({...p,x:p.x+40}))}>←</button><button className="button" aria-label="მარჯვნივ გადაადგილება" onClick={()=>setPos(p=>({...p,x:p.x-40}))}>→</button><button className="button" aria-label="ზემოთ გადაადგილება" onClick={()=>setPos(p=>({...p,y:p.y+40}))}>↑</button><button className="button" aria-label="ქვემოთ გადაადგილება" onClick={()=>setPos(p=>({...p,y:p.y-40}))}>↓</button><a className="button" href={current.src} target="_blank" rel="noreferrer"><ExternalLink size={16}/>ორიგინალი</a></div><p>გადიდება ახალ საინჟინრო დეტალებს არ აღადგენს.</p></dialog></section>;
}
const spots=[{x:.17,y:.43,title:'კორპუსი',text:'ხილული გარე კორპუსი შიდა განლაგებას შემოსაზღვრავს. ზომები და მასალა ამ სურათიდან დადასტურებული არ არის.'},{x:.50,y:.23,title:'ექვსწერტილიანი ზედაპირი',text:'ზედა პანელზე ჩანს ექვსი წერტილის ადგილი. ასოების გამოსახვა ამ საიტზე პროგრამული სიმულაციით ხდება.'},{x:.52,y:.53,title:'შიდა საყრდენები',text:'ხილული ჰორიზონტალური ფირფიტები და ვერტიკალური ნაწილები შიდა განლაგებას აჩვენებს.'},{x:.55,y:.78,title:'ამძრავების არე',text:'შიდა მექანიკური ნაწილების საერთო არე. კონკრეტული ამძრავის ტიპი და მოქმედების სქემა დასაზუსტებელია.'}];
export function Hotspots(){const [active,setActive]=useState(0),[show,setShow]=useState(true);return <div className="hotspot-layout"><div><div className="hotspot-image"><img src={IMAGES[1].src} alt={IMAGES[1].caption}/>{show&&spots.map((s,i)=><button key={s.title} className={active===i?'active':''} style={{left:`${s.x*100}%`,top:`${s.y*100}%`}} aria-label={s.title} aria-pressed={active===i} onClick={()=>setActive(i)}>{i+1}</button>)}</div><button className="button subtle" onClick={()=>setShow(!show)}>{show?'ნიშნულების დამალვა':'ნიშნულების ჩვენება'}</button></div><ol className="hotspot-list">{spots.map((s,i)=><li key={s.title} className={i===active?'active':''}><button onClick={()=>setActive(i)}><span>{i+1}</span>{s.title}</button><p>{s.text}</p></li>)}</ol></div>;}
