import {lazy,Suspense,useEffect,useState} from 'react';
import {ArrowRight,Play,Pause,RotateCcw,ChevronLeft,ChevronRight,Volume2,Box} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import Cell from './Cell';
import {usePinAudio} from './PinSound';
import {convert,dots,unicode,ALPHABET,REVISION,appendRecognition,type RecognitionEvent} from './core';
import {Recorder,useSpeech} from './Speech';
const DeviceViewer=lazy(()=>import('./DeviceViewer'));
export function Lab({learn=false}:{learn?:boolean}){
 const [params]=useSearchParams();const [text,setText]=useState(params.get('text')??'გამარჯობა'),[position,setPosition]=useState(0),[playing,setPlaying]=useState(false),[interval,setIntervalMs]=useState(1000),[raw,setRaw]=useState<RecognitionEvent|null>(null),[correction,setCorrection]=useState(''),[confirmed,setConfirmed]=useState(false),[show3d,setShow3d]=useState(false);
 const [narrate,setNarrate]=useState(true);const pinAudio=usePinAudio();
 const speech=useSpeech();const cells=convert(text),invalid=cells.filter(c=>c.mask===null),current=cells[position];
 useEffect(()=>{setPosition(0);setPlaying(false);},[text]);
 useEffect(()=>{if(!playing||invalid.length||!cells.length)return;const timer=window.setInterval(()=>setPosition(p=>{if(p>=cells.length-1){setPlaying(false);return p;}return p+1;}),interval);return()=>clearInterval(timer);},[playing,interval,text]);
 useEffect(()=>{if(playing&&narrate&&current&&!invalid.length)speech.speak(current.char===' '?'სივრცე':current.char);else speech.stop();return()=>speech.stop();},[playing,position,narrate,text]);
 function choose(char:string){setText(char);setRaw(null);setConfirmed(false);}
 return <><div className="page-heading"><div><p className="eyebrow">{learn?'სწავლა · ქართული ანბანი':'ინტერაქტიული ლაბორატორია'}</p><h1>{learn?'შეისწავლე ექვსი წერტილი':'შენი სიტყვა ბრაილში'}</h1><p>{learn?'აირჩიე ასო და დააკვირდი მის წერტილებს.':'დაწერე ან წარმოთქვი ქართული სიტყვა და გამოიკვლიე თითოეული ასო.'}</p></div><span className="pill"><span className="status-dot"/>პროგრამული სიმულაცია</span></div>
 {learn&&<><div className="lesson-intro"><div><span className="step-number">01</span><h2>ერთი უჯრა. ექვსი წერტილი.</h2><p>მარცხნივ: 1, 2, 3. მარჯვნივ: 4, 5, 6. კითხვის მიმართულებით დალაგებული წერტილების კომბინაცია ასოს ქმნის.</p><p className="muted">ეს ვიზუალური და აუდიტორული სავარჯიშოა; ტაქტილურ კითხვას არ ზომავს.</p></div><Cell mask={0}/><img src="/assets/device/device-top-cell-original.jpeg" alt="ექვსწერტილიანი ზედაპირის დეტალი — SolidWorks-ის რენდერი"/></div><div className="section-heading"><h2>ქართული ანბანი</h2><span>33 ასო · Liblouis</span></div><div className="alphabet">{ALPHABET.map(char=><button key={char} aria-pressed={text===char} onClick={()=>choose(char)}><strong>{char}</strong><span>{unicode(convert(char)[0].mask!)}</span></button>)}</div></>}
 <div className="lab-grid"><section className="panel input-panel"><p className="eyebrow">01 / შეიყვანე სიტყვა</p><h2>ტექსტი ან ხმა</h2><label htmlFor="lab-text">ქართული ტექსტი</label><textarea id="lab-text" value={text} maxLength={160} onChange={e=>{setText(e.target.value);setConfirmed(false);}} rows={3}/><p className="input-help">33 თანამედროვე ქართული ასო და სივრცე. ციფრები და პუნქტუაცია ამ ვერსიაში არ გარდაიქმნება.</p><div className="example-row"><span>სცადე:</span>{['დედა','მზე','წიგნი'].map(s=><button key={s} onClick={()=>choose(s)}>{s}</button>)}</div><div className="divider"><span>ან გამოიყენე მიკროფონი</span></div><Recorder onBusy={busy=>{if(busy){setPlaying(false);setRaw(null);setConfirmed(false);}}} onTranscript={event=>{appendRecognition(event);setRaw(event);setCorrection(event.raw);setConfirmed(false);}}/>
 {raw&&<div className="transcript"><p><strong>გავიგონე:</strong> <span data-testid="raw-transcript">{raw.raw}</span></p><small>{raw.engine} / {raw.model} · ka · {raw.processingMs} მწმ</small><label htmlFor="correction">დაადასტურე ან შეასწორე ტექსტი</label><input id="correction" value={correction} maxLength={160} onChange={e=>{setCorrection(e.target.value);setConfirmed(false);}}/><button className="button primary" disabled={!correction.trim()} onClick={()=>{setText(correction);setConfirmed(true);}}>ტექსტის დადასტურება<ArrowRight size={16}/></button>{confirmed&&<p role="status">{correction===raw.raw?'დადასტურებულია უცვლელი ტექსტი.':'გამოყენებულია ხელით შესწორებული ტექსტი.'}</p>}</div>}
 <Link className="text-link" to="/checks">მიკროფონისა და ხმის შემოწმება <ArrowRight size={15}/></Link></section>
 <section className="panel output-panel"><div className="section-heading"><p className="eyebrow">02 / დააკვირდი წერტილებს</p><button className="icon-button" aria-label="შეყვანილი ტექსტის გახმოვანება" disabled={!text.trim()} onClick={()=>speech.speak(text)}><Volume2 size={20}/></button></div>{invalid.length?<div role="alert" className="error-box"><h3>ზოგი სიმბოლო არ არის მხარდაჭერილი</h3><p>{[...new Set(invalid.map(c=>c.char))].join(' · ')}</p><p>შეცვალე ეს სიმბოლოები. ისინი ჩუმად არ წაიშლება.</p></div>:current?<><div className="current-cell"><div className="letter-display"><span className="muted">მიმდინარე ასო</span><strong>{current.char===' '?'␣':current.char}</strong><span>{position+1} / {cells.length}</span></div><Cell mask={current.mask??0} audible/><div className="dot-readout"><span>წერტილები</span><strong>{dots(current.mask??0).join(' · ')||'სივრცე'}</strong><span className="unicode">{unicode(current.mask??0)}</span></div></div><div className="word-strip" aria-label="სიტყვის ეკრანული მიმოხილვა">{cells.map((c,i)=><button key={i} className={i===position?'active':''} aria-label={`${c.char===' '?'სივრცე':c.char}, პოზიცია ${i+1}`} aria-current={i===position?'step':undefined} onClick={()=>{setPosition(i);setPlaying(false);}}><span>{unicode(c.mask??0)}</span><small>{c.char===' '?'␣':c.char}</small></button>)}</div><div className="player"><div className="actions"><button className="icon-button" aria-label="წინა ასო" disabled={position===0} onClick={()=>{setPlaying(false);setPosition(p=>p-1);}}><ChevronLeft/></button><button className="button primary" disabled={speech.micActive} onClick={()=>{pinAudio?.resume();if(position===cells.length-1&&!playing)setPosition(0);setPlaying(!playing);}}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'პაუზა':'დაკვრა'}</button><button className="icon-button" aria-label="შემდეგი ასო" disabled={position>=cells.length-1} onClick={()=>{setPlaying(false);setPosition(p=>p+1);}}><ChevronRight/></button><button className="icon-button" aria-label="სიტყვის თავიდან დაწყება" onClick={()=>{setPosition(0);setPlaying(false);}}><RotateCcw size={18}/></button></div><label>ინტერვალი<select value={interval} onChange={e=>setIntervalMs(+e.target.value)}><option value={600}>0.6 წამი</option><option value={1000}>1 წამი</option><option value={1800}>1.8 წამი</option></select></label></div></>:<div className="empty"><Cell mask={0}/><p>შეიყვანე პირველი სიტყვა.</p></div>}
 <div className="playback-audio"><label className="check-label"><input type="checkbox" checked={narrate} onChange={e=>setNarrate(e.target.checked)}/>დაკვრისას ასოების გახმოვანება</label>{speech.muted?<p role="status">ხმა გამორთულია. <button className="button subtle" onClick={()=>speech.setMuted(false)}>დაკვრის ხმის ჩართვა</button></p>:<small>„დაკვრა“ კითხულობს მიმდინარე ასოს. სოლენოიდის ხმა ზედა ზოლიდან იმართება.</small>}{speech.error&&<p role="status" className="error">{speech.error}</p>}</div><div className="lab-reference"><img src="/assets/device/device-top-cell-original.jpeg" alt="ექვსწერტილიანი ზედაპირის დეტალი — SolidWorks-ის რენდერი"/><div><strong>დიზაინის საწყისი რენდერი</strong><p>ეს გამოსახულება სტატიკურია. ზემოთ მოცემული უჯრა პროგრამული სიმულაციაა.</p><Link to="/device">მოწყობილობის დათვალიერება ↗</Link></div></div><small className="mapping-ref">მაპინგი: Liblouis ka.utb · {REVISION.slice(0,8)} · <Link to="/project">წყარო და ლიცენზია</Link></small></section></div>
 <div className="section-heading"><div><h2>სიტყვიდან მოძრაობამდე</h2><p>იგივე ექვსი წერტილი სივრცულ მოდელზე.</p></div><button className="button" onClick={()=>setShow3d(!show3d)}><Box size={18}/>{show3d?'3D ხედის დახურვა':'3D ხედის გახსნა'}</button></div>{show3d&&<Suspense fallback={<p>3D მოდელი იტვირთება…</p>}><DeviceViewer mask={invalid.length?0:current?.mask??0}/></Suspense>}
 {learn&&<div className="callout"><div><h2>მზად ხარ სავარჯიშოდ?</h2><p>ამოიცანი ნიმუში ან თავად ააწყვე ექვსწერტილიანი უჯრა.</p></div><Link className="button primary" to="/practice">დაიწყე ბრაილის ტესტი<ArrowRight size={17}/></Link></div>}</>;
}
