import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,Volume2,Check,RotateCcw} from 'lucide-react';
import Cell from './Cell';
import {ALPHABET,LETTERS,WORDS,randomItem,convert,dots,evaluate,dictatedDots,appendAttempt,appendRecognition,currentSession,newSession,setSettings,attempts,BUILD,REVISION,type Attempt,type Outcome,type RecognitionEvent,OUTCOMES} from './core';
import {Recorder,useSpeech} from './Speech';
interface Question {id:string;target:string}
export default function Practice(){
 const [params]=useSearchParams();const speech=useSpeech();const [stage,setStage]=useState<'setup'|'active'|'done'>('setup'),[task,setTask]=useState<'read'|'build'>('read'),[difficulty,setDifficulty]=useState('letter'),[count,setCount]=useState(params.has('trial')?1:5),[maxLength,setMaxLength]=useState(4),[letters,setLetters]=useState(ALPHABET.join('')),[mode,setMode]=useState<'typed'|'voice'>('typed'),[feedback,setFeedback]=useState('immediate'),[timerOn,setTimerOn]=useState(false),[modality,setModality]=useState<'visual'|'auditory'>('visual');
 const [questions,setQuestions]=useState<Question[]>([]),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[mask,setMask]=useState(0),[recognition,setRecognition]=useState<RecognitionEvent|null>(null),[assisted,setAssisted]=useState(false),[result,setResult]=useState<Attempt|null>(null),[retry,setRetry]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[paused,setPaused]=useState(false),[seconds,setSeconds]=useState(0),[session,setSession]=useState(currentSession().id);
 const presented=useRef(Date.now()),asrTotal=useRef(0),pauseAt=useRef(0),pausedMs=useRef(0);
 const question=questions[index],patterns=question?convert(question.target).map(c=>c.mask??0):[];
 useEffect(()=>{if(stage!=='active'||!timerOn||paused||result)return;const t=setInterval(()=>setSeconds(Math.floor((Date.now()-presented.current-pausedMs.current)/1000)),500);return()=>clearInterval(t);},[stage,timerOn,paused,result,index]);
 function resetQuestion(){setAnswer('');setMask(0);setRecognition(null);setAssisted(false);setResult(null);setRetry(0);setMessage('');setBusy(false);setPaused(false);setSeconds(0);asrTotal.current=0;pausedMs.current=0;presented.current=Date.now();speech.stop();}
 function start(targets?:string[]){const pool=[...new Set([...letters].filter(c=>LETTERS[c]!==undefined))];if(!pool.length){setMessage('აირჩიე მინიმუმ ერთი ქართული ასო.');return;}const wordPool=WORDS.filter(w=>w.length<=maxLength&&[...w].every(c=>pool.includes(c)));if(!targets&&task==='read'&&difficulty==='word'&&!wordPool.length){setMessage('ამ ასოებისა და სიგრძისთვის სიტყვა არ მოიძებნა. გააფართოვე არჩევანი.');return;}
 const newS=newSession();setSession(newS.id);setSettings({task,difficulty,count,maxLength,letters:pool.join(''),mode,feedback,timerOn,modality});setQuestions((targets??Array.from({length:count},()=>randomItem(task==='read'&&difficulty==='word'?wordPool:pool))).map(target=>({id:crypto.randomUUID(),target})));setIndex(0);resetQuestion();setStage('active');}
 function record(outcome:Outcome,confirmed:boolean,chosenAnswer=answer,chosenMask:number|null=task==='build'?mask:null){if(!question)return null;const now=Date.now();const total=now-presented.current-pausedMs.current;const a:Attempt={schema:1,id:crypto.randomUUID(),sessionId:session,questionId:question.id,build:BUILD,mappingRevision:REVISION,task,modality:task==='build'?'auditory':modality,target:question.target,patterns,answer:confirmed?chosenAnswer:'',selectedMask:confirmed?chosenMask:null,outcome,assisted,retry,inputMode:task==='build'&&mode==='typed'?'dots':mode,rawTranscript:recognition?.raw??null,corrected:recognition?answer!==recognition.raw:false,confirmed,recognition,voiceEngine:speech.engine,presentedAt:new Date(presented.current).toISOString(),submittedAt:new Date(now).toISOString(),responseMs:Math.max(0,total-asrTotal.current),asrMs:asrTotal.current,totalMs:total};try{appendAttempt(a);}catch{setMessage('შედეგის შენახვა ვერ მოხერხდა. შეამოწმე ბრაუზერის საცავი.');return null;}return a;}
 function submit(){if(result||busy)return;if(task==='read'&&!answer.trim()){setMessage('ჯერ შეიყვანე ან დაადასტურე პასუხი.');return;}const correct=task==='build'?mask===patterns[0]:evaluate(question.target,answer);const a=record(correct?'correct':'incorrect',true,task==='build'?dots(mask).join(','):answer);if(a){setResult(a);speech.speak(feedback==='immediate'?(correct?'სწორია':'პასუხი არასწორია. სწორი პასუხია '+question.target):'პასუხი შენახულია');}}
 function next(){if(index+1>=questions.length){setStage('done');speech.stop();return;}setIndex(i=>i+1);resetQuestion();}
 const rows=attempts().filter(a=>a.sessionId===session);const errors=[...new Set(rows.filter(a=>a.outcome==='incorrect'&&a.retry===0).map(a=>a.target))];
 const instruction=task==='build'?`ააწყვე ასო ${question?.target??''}`:'ამოიცანი ბრაილის ნიმუში. პასუხი თქვი ფორმით: ასო, შემდეგ ასო; ან აკრიფე სიტყვა.';
 return <><div className="page-heading"><div><p className="eyebrow">სწავლა და ტესტი</p><h1>{stage==='done'?'სესია დასრულებულია':'ივარჯიშე შენს ტემპში'}</h1><p>რეალური პასუხები, მკაფიო უკუკავშირი და შენი მცდელობების ისტორია.</p></div><Link className="button" to="/learn">ანბანის ნახვა</Link></div>
 {stage==='setup'&&<div className="practice-setup"><section className="panel"><p className="eyebrow">სესიის პარამეტრები</p><h2>რას ვივარჯიშებთ?</h2><div className="task-options"><button className={task==='read'?'selected':''} aria-pressed={task==='read'} onClick={()=>setTask('read')}><span>⠃</span><strong>ამოიცანი ბრაილი</strong><small>დააკვირდი ნიმუშს და უპასუხე</small></button><button className={task==='build'?'selected':''} aria-pressed={task==='build'} onClick={()=>{setTask('build');setDifficulty('letter');}}><span>⠿</span><strong>ააწყვე ნიმუში</strong><small>მოისმინე ასო და მონიშნე წერტილები</small></button></div><div className="form-grid"><label>დავალებების რაოდენობა<select value={count} onChange={e=>setCount(+e.target.value)}><option value={1}>1 · საცდელი</option><option value={5}>5 დავალება</option><option value={10}>10 დავალება</option></select></label><label>სირთულე<select value={difficulty} onChange={e=>setDifficulty(e.target.value)} disabled={task==='build'}><option value="letter">ასოები</option><option value="word">მოკლე სიტყვები</option></select></label><label>პასუხის შეყვანა<select value={mode} onChange={e=>setMode(e.target.value as 'typed'|'voice')}><option value="typed">კლავიატურა / წერტილები</option><option value="voice">მიკროფონი</option></select></label><label>უკუკავშირი<select value={feedback} onChange={e=>setFeedback(e.target.value)}><option value="immediate">ყოველი პასუხის შემდეგ</option><option value="deferred">სესიის ბოლოს</option></select></label><label>სიტყვის მაქსიმალური სიგრძე<select value={maxLength} disabled={difficulty!=='word'} onChange={e=>setMaxLength(+e.target.value)}>{[2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>სავარჯიშოს აღქმა<select value={modality} onChange={e=>setModality(e.target.value as 'visual'|'auditory')}><option value="visual">ვიზუალური ნიმუში</option><option value="auditory">წერტილების მოსმენა</option></select></label></div><label>სავარჯიშო ასოები<input value={letters} onChange={e=>setLetters(e.target.value)} aria-describedby="letters-help"/></label><small id="letters-help">შეიყვანე სასურველი ქართული ასოები. სიტყვები შეირჩევა მხოლოდ ამ ასოებით.</small><label className="check-label"><input type="checkbox" checked={timerOn} onChange={e=>setTimerOn(e.target.checked)}/>დროის ჩვენება (დროის შეზღუდვის გარეშე)</label>{message&&<p role="alert" className="error">{message}</p>}<button className="button primary wide" onClick={()=>start()}>სესიის დაწყება<ArrowRight size={18}/></button></section><aside className="practice-aside"><Cell mask={11}/><h2>პატარა ნაბიჯებით,<br/>ასოდან სიტყვამდე.</h2><p>ჯერ გაეცანი ექვსი წერტილის განლაგებას. შემდეგ სცადე მოკლე სესია.</p><ul><li>მინიშნება მცდელობას მონიშნავს დახმარებით შესრულებულად.</li><li>ხმის ამოცნობის შეცდომა სწავლის შეცდომად არ ითვლება.</li><li>შედეგები ინახება ამ ბრაუზერში.</li></ul><p className="small-note">სესიის სიგრძე დემოს პარამეტრია, არა მეცნიერულად დადასტურებული შეფასების ინსტრუმენტი.</p></aside></div>}
 {stage==='active'&&question&&<section className="panel exercise"><div className="section-heading"><span className="pill">დავალება {index+1} / {questions.length}</span><span>{task==='build'?'ნიმუშის აწყობა':modality==='auditory'?'აუდიტორული წერტილების სავარჯიშო':'ვიზუალური ნიმუშის ამოცნობა'}{timerOn?` · ${seconds} წმ`:''}</span></div><progress value={index} max={questions.length} aria-label="სესიის პროგრესი"/><h2>{task==='build'?`ააწყვე ასო „${question.target}“`:'რომელი ასო ან სიტყვაა?'}</h2><button className="button subtle" onClick={()=>speech.speak(modality==='auditory'&&task==='read'?patterns.map((p,i)=>`უჯრა ${i+1}. წერტილები ${dots(p).join(', ')}`).join('. '):instruction)}><Volume2 size={17}/>ინსტრუქციის გამეორება</button>
 {paused?<div className="empty"><h3>სესია შეჩერებულია</h3><p>გასაგრძელებლად დააჭირე ქვედა ღილაკს.</p></div>:<><div className="exercise-pattern">{task==='build'?<Cell mask={mask} audible interactive={!result} onChange={setMask}/>:patterns.map((p,i)=><Cell key={i} mask={p} small={patterns.length>1} audible/>)}</div><p className="muted">{task==='build'?'მონიშნე წერტილები. კლავიატურით: Tab, Space ან ფოკუსირებულ უჯრაზე 1–6.':'ეკრანული ნიმუში; ტაქტილურ კითხვას არ ამოწმებს.'}</p>
 {!result&&<><label>შეყვანის რეჟიმი<select value={mode} disabled={busy} onChange={e=>{setMode(e.target.value as 'typed'|'voice');setRecognition(null);setAnswer('');}}><option value="typed">კლავიატურა / წერტილები</option><option value="voice">მიკროფონი</option></select></label>{mode==='voice'&&<><p>{task==='build'?'თქვი წერტილების ნომრები: ერთი, ორი, სამი, ოთხი, ხუთი, ექვსი.':'თქვი ასო ან სიტყვა; იზოლირებული ასოს ამოცნობა ყოველთვის ზუსტი არ არის. შედეგი შეამოწმე.'}</p><Recorder key={`${question.id}-${retry}`} onBusy={b=>{setBusy(b);if(b){setRecognition(null);setAnswer('');}}} onTranscript={event=>{asrTotal.current+=event.processingMs;appendRecognition(event,question.id);setRecognition(event);setAnswer(event.raw);}} onIssue={(state,msg)=>{record(state,false);setMessage(msg);}}/>{recognition&&<div className="transcript"><p><strong>გავიგონე:</strong> <span data-testid="raw-transcript">{recognition.raw}</span></p><small>{recognition.engine} / {recognition.model} · ka · {recognition.processingMs} მწმ</small></div>}</>}
 {(task==='read'||mode==='voice')&&<label htmlFor="answer">{task==='build'?'ამოცნობილი ნომრები — შეამოწმე':'შენი პასუხი — შეამოწმე და დაადასტურე'}<input id="answer" value={answer} disabled={busy} maxLength={160} onChange={e=>setAnswer(e.target.value)} autoComplete="off"/></label>}{task==='build'&&mode==='voice'&&<button className="button" disabled={!answer.trim()||busy} onClick={()=>{const m=dictatedDots(answer);if(m===null)setMessage('გამოიყენე მხოლოდ ნომრები 1–6 ან მათი ქართული სახელები.');else{setMask(m);setMessage('ნომრები გადატანილია უჯრაზე. შეამოწმე და დაადასტურე.');}}}>ნომრების უჯრაზე გადატანა</button>}
 {message&&<p role="status" className="error">{message}</p>}{assisted&&<p className="hint">მინიშნება: {question.target} · {patterns.map(p=>dots(p).join(', ')).join(' / ')}</p>}<div className="actions"><button className="button primary" disabled={busy||(task==='read'&&!answer.trim())} onClick={submit}><Check size={18}/>პასუხის დადასტურება</button><button className="button" disabled={busy} onClick={()=>setAssisted(true)}>მინიშნება</button><button className="button subtle" disabled={busy} onClick={()=>{record('skipped',false);next();}}>გამოტოვება</button></div></>}
 {result&&<div role="status" className={`feedback ${feedback==='deferred'?'neutral':result.outcome==='correct'?'success':'failure'}`}><h3>{feedback==='deferred'?'პასუხი შენახულია':OUTCOMES[result.outcome]}</h3>{feedback==='immediate'&&<p>სწორი პასუხი: <strong>{question.target}</strong> · წერტილები {patterns.map(p=>dots(p).join(', ')).join(' / ')}</p>}{task==='build'&&feedback==='immediate'&&<p>დასამატებელი: {dots(patterns[0]&~mask).join(', ')||'არცერთი'} · მოსახსნელი: {dots(mask&~patterns[0]).join(', ')||'არცერთი'}</p>}<div className="actions"><button className="button primary" onClick={next}>{index+1===questions.length?'სესიის დასრულება':'შემდეგი დავალება'}<ArrowRight size={17}/></button>{feedback==='immediate'&&<button className="button" onClick={()=>{presented.current=Date.now();asrTotal.current=0;pausedMs.current=0;setSeconds(0);setResult(null);setRetry(r=>r+1);setAssisted(true);setAnswer('');setRecognition(null);setMask(0);setMessage('განმეორება ინახება ცალკე; პირველი პასუხი უცვლელი რჩება.');}}><RotateCcw size={16}/>ხელახლა ცდა</button>}</div></div>}</>}
 <div className="exercise-footer"><button className="button subtle" disabled={busy||Boolean(result)} onClick={()=>{if(paused)pausedMs.current+=Date.now()-pauseAt.current;else{pauseAt.current=Date.now();speech.stop();}setPaused(!paused);}}>{paused?'გაგრძელება':'პაუზა'}</button><button className="button subtle" onClick={()=>{if(!result)record('cancelled',false);speech.stop();setStage('done');}}>სესიის დასრულება ახლა</button></div></section>}
 {stage==='done'&&<section className="panel"><p className="eyebrow">შენახული მცდელობები</p><h2>გადახედე შენს პასუხებს</h2><p>პირველი პასუხი და განმეორებითი ცდები ცალკე ინახება.</p><div className="review-items">{rows.filter(r=>r.confirmed||r.outcome==='skipped').map(row=><div className="review-item" key={row.id}><div className="mini-patterns">{row.patterns.map((p,i)=><Cell key={i} mask={p} small/>)}</div><div><strong>{row.target}</strong><p>პასუხი: {row.answer||'—'}</p><small>{row.assisted?'დახმარებით':'დახმარების გარეშე'} · {OUTCOMES[row.outcome]}</small></div></div>)}</div><div className="actions"><Link className="button primary" to="/results">სრული შედეგები და ექსპორტი<ArrowRight size={17}/></Link>{errors.length>0&&<button className="button" onClick={()=>start(errors)}>შეცდომიანი ნიმუშების გამეორება ({errors.length})</button>}<button className="button" onClick={()=>{setStage('setup');setMessage('');}}>ახალი სესიის მომზადება</button></div></section>}</>;
}
