import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import { Mic,Square,X,Volume2,VolumeX,Pause,Play } from 'lucide-react';
import type {RecognitionEvent} from './core';
import {withTimeout} from './request';
export interface Health {model_state:string;model:string;engine:string;voice_available:boolean;voice_engine:string|null;max_audio_seconds:number;device:string;compute_type:string;build:string;timestamp:string}
export async function getHealth():Promise<Health>{return withTimeout(async signal=>{const r=await fetch('/api/health',{signal});if(!r.ok)throw Error('ხმოვანი სერვისი მიუწვდომელია.');return r.json();},5000);}
const SpeechContext=createContext<{speak:(text:string)=>void;stop:()=>void;engine:string|null;error:string;muted:boolean;setMuted:(v:boolean)=>void;rate:number;setRate:(v:number)=>void;pause:()=>void;resume:()=>void;micActive:boolean;setMicActive:(active:boolean)=>void}>({} as never);
export const useSpeech=()=>useContext(SpeechContext);
export function SpeechProvider({children}:{children:ReactNode}){
 const [engine,setEngine]=useState<string|null>(null),[error,setError]=useState(''),[muted,setMuted]=useState(false),[rate,setRate]=useState(150);
 const [micActive,setMicActive]=useState(false);const micRef=useRef(false);
 const audio=useRef<HTMLAudioElement|null>(null),controller=useRef<AbortController|null>(null),sequence=useRef(0),audioURL=useRef('');
 useEffect(()=>{getHealth().then(h=>setEngine(h.voice_available?h.voice_engine:null)).catch(()=>{});return()=>stop();},[]);
 function stop(){sequence.current++;controller.current?.abort();audio.current?.pause();audio.current=null;if(audioURL.current)URL.revokeObjectURL(audioURL.current);audioURL.current='';}
 async function speak(text:string){stop();setError('');if(muted||micRef.current||!text.trim())return;const id=sequence.current;
  try{controller.current=new AbortController();const blob=await withTimeout(async signal=>{const r=await fetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,rate}),signal});if(!r.ok){const e=await r.json();throw Error(e.detail||'ქართული ხმა მიუწვდომელია.');}return r.blob();},25000,controller.current.signal);if(id!==sequence.current)return;audioURL.current=URL.createObjectURL(blob);audio.current=new Audio(audioURL.current);await audio.current.play();}catch(e){if(id===sequence.current)setError(e instanceof Error?e.message:'ხმა მიუწვდომელია.');}
 }
 return <SpeechContext.Provider value={{speak,stop,engine,error,muted,setMuted:v=>{stop();setMuted(v);},rate,setRate,micActive,setMicActive:v=>{micRef.current=v;setMicActive(v);},pause:()=>{audio.current?.pause();},resume:()=>{if(micRef.current)return;void audio.current?.play();}}}>{children}</SpeechContext.Provider>;
}
export function VoiceTools(){const s=useSpeech();return <div className="voice-tools"><button className="icon-button" aria-label={s.muted?'ხმის ჩართვა':'ხმის გამორთვა'} onClick={()=>s.setMuted(!s.muted)}>{s.muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><button className="icon-button" aria-label="ხმის შეჩერება" onClick={s.pause}><Pause size={16}/></button><button className="icon-button" aria-label="ხმის გაგრძელება" onClick={s.resume}><Play size={16}/></button><button className="icon-button" aria-label="გახმოვანების დასრულება" onClick={s.stop}><Square size={16}/></button><label className="sr-only" htmlFor="voice-rate">ხმის სიჩქარე</label><select id="voice-rate" value={s.rate} onChange={e=>s.setRate(+e.target.value)}><option value="110">ნელი ხმა</option><option value="150">ჩვეულებრივი ხმა</option><option value="190">სწრაფი ხმა</option></select>{s.error&&<span role="status" className="error">{s.error}</span>}</div>;}
export function Recorder({onTranscript,onIssue,onBusy}:{onTranscript:(event:RecognitionEvent)=>void;onIssue?:(state:'cancelled'|'recognition-unresolved'|'technical-failure',message:string)=>void;onBusy?:(busy:boolean)=>void}){
 const speech=useSpeech();const [state,setState]=useState<'idle'|'permission'|'recording'|'processing'>('idle'),[error,setError]=useState(''),[level,setLevel]=useState(0),[elapsed,setElapsed]=useState(0);
 const stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),ctx=useRef<AudioContext|null>(null),frame=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null),abort=useRef<AbortController|null>(null),seq=useRef(0),startAt=useRef(''),chunks=useRef<Blob[]>([]),mounted=useRef(true);
 function release(){speech.setMicActive(false);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(ctx.current){void ctx.current.close();ctx.current=null;}cancelAnimationFrame(frame.current);if(timer.current)clearInterval(timer.current);timer.current=null;}
 function cancel(report=true){seq.current++;abort.current?.abort();if(recorder.current?.state==='recording'){recorder.current.onstop=null;recorder.current.stop();}release();if(mounted.current){setState('idle');setLevel(0);onBusy?.(false);if(report)onIssue?.('cancelled','ჩანაწერი გაუქმებულია.');}}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;cancel(false);};},[]);
 async function start(){speech.stop();setError('');const generation=++seq.current;setState('permission');onBusy?.(true);
  try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('ჩაწერა მიუწვდომელია. გამოიყენეთ localhost / HTTPS ან ტექსტის შეყვანა.');
   const h=await getHealth();if(generation!==seq.current)return;if(h.model_state!=='ready')throw Error('მეტყველების მოდელი მზად არ არის. შეამოწმეთ სერვისი ან გამოიყენეთ ტექსტი.');
   const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(generation!==seq.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;
   const type=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));if(!type)throw Error('ბრაუზერი მხარდაჭერილ აუდიოფორმატს ვერ წერს. სცადეთ სხვა ბრაუზერი ან ტექსტი.');
   speech.setMicActive(true);recorder.current=new MediaRecorder(s,{mimeType:type});chunks.current=[];recorder.current.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);};
   recorder.current.onerror=()=>{cancel(false);setError('მიკროფონის ჩაწერა შეწყდა. გაიმეორეთ ან შეიყვანეთ ტექსტი.');onIssue?.('technical-failure','ჩაწერის შეცდომა');};
   recorder.current.onstop=()=>void submit(generation,type,h.model);
   ctx.current=new AudioContext();const analyser=ctx.current.createAnalyser();analyser.fftSize=256;ctx.current.createMediaStreamSource(s).connect(analyser);const values=new Uint8Array(analyser.fftSize);
   const tick=()=>{analyser.getByteTimeDomainData(values);const rms=Math.sqrt(values.reduce((a,x)=>a+(x-128)**2,0)/values.length)/128;setLevel(Math.min(1,rms*5));frame.current=requestAnimationFrame(tick);};tick();
   startAt.current=new Date().toISOString();setElapsed(0);recorder.current.start(250);setState('recording');let seconds=0;timer.current=setInterval(()=>{setElapsed(++seconds);if(seconds>=Math.min(30,h.max_audio_seconds))stop();},1000);
  }catch(e){if(generation!==seq.current)return;release();setState('idle');onBusy?.(false);const message=e instanceof DOMException&&e.name==='NotAllowedError'?'მიკროფონზე წვდომა არ არის დაშვებული. დაუშვით წვდომა ან შეიყვანეთ ტექსტი.':e instanceof DOMException&&e.name==='NotFoundError'?'მიკროფონი ვერ მოიძებნა. გამოიყენეთ ტექსტის შეყვანა.':e instanceof TypeError?'ხმოვანი სერვისი მიუწვდომელია. გამოიყენეთ ტექსტის შეყვანა.':e instanceof Error?e.message:'მიკროფონი დაკავებულია ან მიუწვდომელია.';setError(message);onIssue?.('technical-failure',message);}
 }
 function stop(){if(recorder.current?.state==='recording'){recorder.current.stop();release();setState('processing');setLevel(0);}}
 async function submit(generation:number,type:string,model:string){const ended=new Date().toISOString();release();if(generation!==seq.current)return;
  try{abort.current=new AbortController();const form=new FormData();form.append('audio',new Blob(chunks.current,{type}),type.includes('mp4')?'recording.mp4':type.includes('ogg')?'recording.ogg':'recording.webm');chunks.current=[];
   const data=await withTimeout(async signal=>{const r=await fetch('/api/transcribe',{method:'POST',body:form,signal});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'ამოცნობა ვერ შესრულდა. სცადეთ ხელახლა.');return data;},120000,abort.current.signal);if(generation!==seq.current)return;
   if(data.state==='no-speech'){setError('მეტყველება ვერ ამოიცნო. გაიმეორეთ ან შეიყვანეთ პასუხი ტექსტით.');onIssue?.('recognition-unresolved','მეტყველება ვერ ამოიცნო.');}
   else onTranscript({schema:1,raw:data.raw_transcript,engine:data.engine,model:data.model??model,recordingStartedAt:startAt.current,recordingEndedAt:ended,processingStartedAt:data.processing_started_at,processingEndedAt:data.processing_ended_at,processingMs:data.processing_ms,state:data.state});
  }catch(e){if(generation===seq.current){const message=e instanceof Error&&e.name==='TimeoutError'?'ამოცნობის დრო ამოიწურა. გაიმეორეთ ან შეიყვანეთ ტექსტი.':e instanceof TypeError?'ხმოვან სერვისთან დაკავშირება ვერ მოხერხდა. გამოიყენე ტექსტი.':e instanceof Error?e.message:'ხმოვანი სერვისი მიუწვდომელია.';setError(message);onIssue?.('technical-failure',message);}}
  finally{if(generation===seq.current){setState('idle');onBusy?.(false);}}
 }
 return <div className="recorder"><div className="actions">{state==='idle'?<button type="button" className="button primary" onClick={()=>void start()}><Mic size={18}/>სცადე ხმით</button>:state==='recording'?<button type="button" className="button recording" onClick={stop}><Square size={17}/>ჩაწერის დასრულება</button>:<span className="pill">{state==='permission'?'მიკროფონის მომზადება…':'მეტყველების ამოცნობა…'}</span>}{state!=='idle'&&<button type="button" className="button subtle" onClick={()=>cancel()}><X size={16}/>გაუქმება</button>}</div><div className="mic-meter" role="meter" aria-label="მიკროფონის დონის მაჩვენებელი" aria-valuenow={Math.round(level*100)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${level*100}%`}}/></div><small aria-live="polite">{state==='recording'?`იწერება · ${elapsed} / 30 წმ`:'მაქსიმუმ 30 წამი · ქართული · ადგილობრივი ამოცნობა'}</small>{error&&<p role="alert" className="error">{error}</p>}</div>;
}
